# NumPy

# NumPy Array

In [47]:
import numpy as np

In [48]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
my_list = list(range(10))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
print(type(array))
print(type(my_list))
print(type(array.dtype))

<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.dtypes.Int64DType'>


In [51]:
for i in range(10):array_2 = array * 2
array_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
for i in range(10):my_list = [i * 2 for i in my_list]
my_list

[0, 1024, 2048, 3072, 4096, 5120, 6144, 7168, 8192, 9216]

In [55]:
num = np.random.randn(3,3)
num

array([[-1.29880996,  0.75800344,  0.54494304],
       [-0.15581476,  1.16829601, -0.70088475],
       [ 0.09536006, -0.13366083,  0.07505955]])

In [54]:
num * 3

array([[ 0.17286269, -0.69053513, -0.38138809],
       [ 1.47005689, -2.03075406,  1.34861884],
       [ 2.26249159,  2.06728564, -1.74220367]])

In [56]:
arr = np.arange(64).reshape(8,8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [57]:
arr.shape

(8, 8)

In [62]:
arr.ndim

2

In [63]:
arr3d = arr.reshape(4,4,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [66]:
arr4d = arr.reshape(8,2,4)
print(arr4d)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [67]:
arr = np.zeros_like(arr3d)
arr

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [74]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [75]:
data = np.zeros((3,3))
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
data = np.ones((5,5))
data

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
data = np.eye(3,3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
data = np.full(2,5)
data

array([5, 5])

In [82]:
data = np.full((5,5),10)
print(data)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [83]:
my_list = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
my_list[1,2]

6

In [85]:
n1 = np.arange(36).reshape(6,6)
n2 = np.arange(36).reshape(6,6)
n1 * n2

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [86]:
n1 @ n2

array([[ 330,  345,  360,  375,  390,  405],
       [ 870,  921,  972, 1023, 1074, 1125],
       [1410, 1497, 1584, 1671, 1758, 1845],
       [1950, 2073, 2196, 2319, 2442, 2565],
       [2490, 2649, 2808, 2967, 3126, 3285],
       [3030, 3225, 3420, 3615, 3810, 4005]])

# Numpy Array Basic Indexing & slicing

In [7]:
import numpy as np

In [9]:
arr2d = np.arange(25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
arr2d[4,4]

24

In [14]:
arr2d[3][3]

18

In [17]:
arr3d = np.arange(50).reshape(2,5,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [19]:
arr1d = np.arange(15)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
sliced = arr1d[4:10:2]
sliced

array([4, 6, 8])

In [27]:
sliced = arr1d[-6:-1:2]
sliced

array([ 9, 11, 13])

In [29]:
arr2d[3:5,1:3]

[ 0,  1,  2,  3,  4],
[ 5,  6,  7,  8,  9],
[10, 11, 12, 13, 14],
[15, 16, 17, 18, 19],
[20, 21, 22, 23, 24]

array([[16, 17],
       [21, 22]])

In [33]:
arr2d[0:,4:]

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

# NumPy Array Boolean Indexing

In [43]:
import numpy as np

In [44]:
name = np.array(["Abdul Subhan", "Abdullah", "Abdul Rehman", "Areeba", "Eman", "Ummi"])
print(name)

['Abdul Subhan' 'Abdullah' 'Abdul Rehman' 'Areeba' 'Eman' 'Ummi']


In [45]:
data = np.random.randn(3,3)
data

array([[ 1.13643841, -1.82330121,  1.60945684],
       [ 0.6348076 , -1.36790389,  2.13219192],
       [ 0.78190703, -0.36502846,  1.54404143]])

In [47]:
name == "Areeba"

array([False, False, False,  True, False, False])

In [57]:
arr = np.arange(45).reshape(9,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [58]:
arr[[1,3,5,7]]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [59]:
arr[[True,False,False,True,False,False,True,False,True]]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [61]:
arr < 40

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [63]:
arr[arr < 40]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [65]:
data = np.array([2,4,6,8,5,8,4,0,9]).reshape(3,3)
data

array([[2, 4, 6],
       [8, 5, 8],
       [4, 0, 9]])

In [66]:
data % 2 == 0

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [67]:
data[data % 2 == 0]

array([2, 4, 6, 8, 8, 4, 0])

In [69]:
data[[0,2]]

array([[2, 4, 6],
       [4, 0, 9]])