# NumPy

# NumPy Array

In [ ]:
import numpy as np

In [ ]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
my_list = list(range(10))
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
print(type(array))
print(type(my_list))
print(type(array.dtype))

<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.dtypes.Int64DType'>


In [ ]:
for i in range(10):array_2 = array * 2
print(array_2)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
for i in range(10):my_list = [i * 2 for i in my_list]
print(my_list)

[0, 1024, 2048, 3072, 4096, 5120, 6144, 7168, 8192, 9216]


In [ ]:
num = np.random.randn(3,3)
print(num)

[[ 1.2629305  -1.89762114  0.02108585]
 [ 0.00971457  0.89016231 -0.16750247]
 [ 1.42598653  0.38027927  0.01420449]]


In [ ]:
print(num * 3)

[[ 3.78879151 -5.69286341  0.06325756]
 [ 0.02914372  2.67048692 -0.50250742]
 [ 4.2779596   1.14083782  0.04261347]]


In [ ]:
arr = np.arange(50).reshape(5,10)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [ ]:
print(arr.shape)

(5, 10)


In [ ]:
print(arr.ndim)

2


In [ ]:
arr3d = arr.reshape(2,5,5)
print(arr3d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [ ]:
arr4d = arr.reshape(5,2,5)
print(arr4d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]]


In [ ]:
arr = np.zeros_like(arr3d)
print(arr)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [ ]:
arr = np.zeros(3)
print(arr)

[0. 0. 0.]


In [ ]:
data = np.zeros((3,3))
print(data)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
data = np.ones((5,5))
print(data)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
data = np.eye(3,5)
print(data)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
data = np.full(2,5)
print(data)

[5 5]


In [ ]:
data = np.full((5,5),10)
print(data)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [ ]:
my_list = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_list)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(my_list[1,2])

6


In [ ]:
n1 = np.arange(36).reshape(6,6)
n2 = np.arange(36).reshape(6,6)
print(n1 * n2)

[[   0    1    4    9   16   25]
 [  36   49   64   81  100  121]
 [ 144  169  196  225  256  289]
 [ 324  361  400  441  484  529]
 [ 576  625  676  729  784  841]
 [ 900  961 1024 1089 1156 1225]]


In [ ]:
print(n1 @ n2)

[[ 330  345  360  375  390  405]
 [ 870  921  972 1023 1074 1125]
 [1410 1497 1584 1671 1758 1845]
 [1950 2073 2196 2319 2442 2565]
 [2490 2649 2808 2967 3126 3285]
 [3030 3225 3420 3615 3810 4005]]


# Numpy Array Basic Indexing & slicing

In [ ]:
import numpy as np

In [ ]:
arr2d = np.arange(25).reshape(5,5)
print(arr2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
print(arr2d[4,4])

24


In [ ]:
print(arr2d[3][3])

18


In [ ]:
arr3d = np.arange(50).reshape(2,5,5)
print(arr3d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [ ]:
arr1d = np.arange(15)
print(arr1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
sliced = arr1d[4:10:2]
print(sliced)

[4 6 8]


In [ ]:
sliced = arr1d[-6:-1:2]
print(sliced)

[ 9 11 13]


In [ ]:
print(arr2d[3:5,1:3])

[[16 17]
 [21 22]]


In [ ]:
print(arr2d[0:,4:])

[[ 4]
 [ 9]
 [14]
 [19]
 [24]]


# NumPy Array Boolean Indexing

In [ ]:
import numpy as np

In [ ]:
name = np.array(["Abdul Subhan", "Abdullah", "Abdul Rehman", "Areeba", "Eman", "Ummi"])
print(name)

['Abdul Subhan' 'Abdullah' 'Abdul Rehman' 'Areeba' 'Eman' 'Ummi']


In [ ]:
data = np.random.randn(3,3)
print(data)

[[-0.66653942  0.61089399 -0.64601632]
 [ 0.02509201 -0.46829041  0.09260105]
 [ 0.23470269 -0.30289429 -1.10586495]]


In [ ]:
print(name == "Areeba")

[False False False  True False False]


In [ ]:
arr = np.arange(45).reshape(9,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


In [ ]:
print(arr[[1,3,5,7]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]]


In [ ]:
print(arr[[True,False,False,True,False,False,True,False,True]])

[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [ ]:
print(arr < 40)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]]


In [ ]:
print(arr[arr < 40])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [ ]:
data = np.array([2,4,6,8,5,8,4,0,9]).reshape(3,3)
print(data)

[[2 4 6]
 [8 5 8]
 [4 0 9]]


In [ ]:
print(data % 2 == 0)

[[ True  True  True]
 [ True False  True]
 [ True  True False]]


In [ ]:
print(data[data % 2 == 0])

[2 4 6 8 8 4 0]


In [ ]:
print(data[[0,2]])

[[2 4 6]
 [4 0 9]]
