# NumPy

# NumPy Array

In [1]:
import numpy as np

In [2]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
my_list = list(range(10))
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
print(type(array))
print(type(my_list))
print(type(array.dtype))

<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.dtypes.Int64DType'>


In [5]:
for i in range(10):array_2 = array * 2
print(array_2)

[ 0  2  4  6  8 10 12 14 16 18]


In [6]:
for i in range(10):my_list = [i * 2 for i in my_list]
print(my_list)

[0, 1024, 2048, 3072, 4096, 5120, 6144, 7168, 8192, 9216]


In [7]:
num = np.random.randn(3,3)
print(num)

[[ 0.88048874  0.26344377 -0.01766469]
 [ 0.44115179  1.23327681 -0.40643226]
 [-0.57640798  0.85445139 -0.30166031]]


In [8]:
print(num * 3)

[[ 2.64146623  0.7903313  -0.05299407]
 [ 1.32345538  3.69983044 -1.21929677]
 [-1.72922395  2.56335417 -0.90498093]]


In [9]:
arr = np.arange(50).reshape(5,10)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [10]:
print(arr.shape)

(5, 10)


In [11]:
print(arr.ndim)

2


In [12]:
arr3d = arr.reshape(2,5,5)
print(arr3d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [13]:
arr4d = arr.reshape(5,2,5)
print(arr4d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]]


In [14]:
arr = np.zeros_like(arr3d)
print(arr)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [15]:
arr = np.zeros(3)
print(arr)

[0. 0. 0.]


In [16]:
data = np.zeros((3,3))
print(data)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
data = np.ones((5,5))
print(data)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
data = np.eye(3,5)
print(data)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [19]:
data = np.full(2,5)
print(data)

[5 5]


In [20]:
data = np.full((5,5),10)
print(data)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [21]:
my_list = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_list)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(my_list[1,2])

6


In [23]:
n1 = np.arange(36).reshape(6,6)
n2 = np.arange(36).reshape(6,6)
print(n1 * n2)

[[   0    1    4    9   16   25]
 [  36   49   64   81  100  121]
 [ 144  169  196  225  256  289]
 [ 324  361  400  441  484  529]
 [ 576  625  676  729  784  841]
 [ 900  961 1024 1089 1156 1225]]


In [24]:
print(n1 @ n2)

[[ 330  345  360  375  390  405]
 [ 870  921  972 1023 1074 1125]
 [1410 1497 1584 1671 1758 1845]
 [1950 2073 2196 2319 2442 2565]
 [2490 2649 2808 2967 3126 3285]
 [3030 3225 3420 3615 3810 4005]]


# Numpy Array Basic Indexing & slicing

In [25]:
import numpy as np

In [26]:
arr2d = np.arange(25).reshape(5,5)
print(arr2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [27]:
print(arr2d[4,4])

24


In [28]:
print(arr2d[3][3])

18


In [29]:
arr3d = np.arange(50).reshape(2,5,5)
print(arr3d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [30]:
arr1d = np.arange(15)
print(arr1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [31]:
sliced = arr1d[4:10:2]
print(sliced)

[4 6 8]


In [32]:
sliced = arr1d[-6:-1:2]
print(sliced)

[ 9 11 13]


In [33]:
print(arr2d[3:5,1:3])

[[16 17]
 [21 22]]


In [34]:
print(arr2d[0:,4:])

[[ 4]
 [ 9]
 [14]
 [19]
 [24]]


# NumPy Array Boolean Indexing

In [35]:
import numpy as np

In [36]:
name = np.array(["Abdul Subhan", "Abdullah", "Abdul Rehman", "Areeba", "Eman", "Ummi"])
print(name)

['Abdul Subhan' 'Abdullah' 'Abdul Rehman' 'Areeba' 'Eman' 'Ummi']


In [37]:
data = np.random.randn(3,3)
print(data)

[[ 0.22194373  0.67075178  0.22233194]
 [-2.83522005  1.57424306  1.28752499]
 [-0.34831667 -0.39776691 -1.49589982]]


In [38]:
print(name == "Areeba")

[False False False  True False False]


In [39]:
arr = np.arange(45).reshape(9,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


In [40]:
print(arr[[1,3,5,7]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]]


In [41]:
print(arr[[True,False,False,True,False,False,True,False,True]])

[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [42]:
print(arr < 40)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]]


In [43]:
print(arr[arr < 40])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [44]:
data = np.array([2,4,6,8,5,8,4,0,9]).reshape(3,3)
print(data)

[[2 4 6]
 [8 5 8]
 [4 0 9]]


In [45]:
print(data % 2 == 0)

[[ True  True  True]
 [ True False  True]
 [ True  True False]]


In [46]:
print(data[data % 2 == 0])

[2 4 6 8 8 4 0]


In [47]:
print(data[[0,2]])

[[2 4 6]
 [4 0 9]]
