In [ ]:
import pandas as pd

In [ ]:
series_1 = pd.Series([17,18,19,20,21,22,23,24,25,26])
print(series_1)

0    17
1    18
2    19
3    20
4    21
5    22
6    23
7    24
8    25
9    26
dtype: int64


In [ ]:
series_1 = pd.Series(["Abdul Subhan","Abdullah","Abdul Rehman","Areeba","Eman","Ummi"],["One","Two","Three","Four","Five","Six"])
print(series_1)

One      Abdul Subhan
Two          Abdullah
Three    Abdul Rehman
Four           Areeba
Five             Eman
Six              Ummi
dtype: object


In [ ]:
print(series_1["Five"])

Eman


In [ ]:
print(series_1["Two":"Five"])

Two          Abdullah
Three    Abdul Rehman
Four           Areeba
Five             Eman
dtype: object


In [ ]:
print(series_1[2:5])

Three    Abdul Rehman
Four           Areeba
Five             Eman
dtype: object


In [ ]:
print(series_1['One':"Six":2])

One      Abdul Subhan
Three    Abdul Rehman
Five             Eman
dtype: object


In [ ]:
series_1["Six"] = "Nazia"
print(series_1)

One      Abdul Subhan
Two          Abdullah
Three    Abdul Rehman
Four           Areeba
Five             Eman
Six             Nazia
dtype: object


In [ ]:
series_1["Two":"Three"] = "Adan","Sejeel"
print(series_1)

One      Abdul Subhan
Two              Adan
Three          Sejeel
Four           Areeba
Five             Eman
Six             Nazia
dtype: object


In [ ]:
print(series_1.values)

['Abdul Subhan' 'Adan' 'Sejeel' 'Areeba' 'Eman' 'Nazia']


In [ ]:
print(series_1.index)

Index(['One', 'Two', 'Three', 'Four', 'Five', 'Six'], dtype='object')


In [ ]:
series_1.index = (['A','B','C','D','E','F'])
print(series_1)

A    Abdul Subhan
B            Adan
C          Sejeel
D          Areeba
E            Eman
F           Nazia
dtype: object


In [ ]:
series_2 = pd.Series({"Islamabad":100, "Karachi":200, "Lahore":300, "Queta":400,"Peshawer":500, "Multan":600})
print(series_2)

Islamabad    100
Karachi      200
Lahore       300
Queta        400
Peshawer     500
Multan       600
dtype: int64


In [ ]:
series_3 = pd.Series(["Karachi", "Hyderabad", "Queta", "Chaman", "Multan", "Faisalabad"])
series_4 = pd.Series(series_2, index = series_3)
print(series_4)

Karachi       200.0
Hyderabad       NaN
Queta         400.0
Chaman          NaN
Multan        600.0
Faisalabad      NaN
dtype: float64


In [ ]:
print(series_4.isnull())

Karachi       False
Hyderabad      True
Queta         False
Chaman         True
Multan        False
Faisalabad     True
dtype: bool


In [ ]:
print(series_4[series_4.isnull()])

Hyderabad    NaN
Chaman       NaN
Faisalabad   NaN
dtype: float64


In [ ]:
print(series_4.isnull().sum())

3


In [ ]:
print(series_4.notnull())

Karachi        True
Hyderabad     False
Queta          True
Chaman        False
Multan         True
Faisalabad    False
dtype: bool


In [ ]:
print(series_4[series_4.notnull()])

Karachi    200.0
Queta      400.0
Multan     600.0
dtype: float64


In [ ]:
print(series_4.notnull().sum())

3


In [ ]:
import numpy as np

In [ ]:
series_5 = pd.Series([10,20,30,40,50,60])
print(series_5)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64


In [ ]:
series_6 = pd.Series([np.NaN,70,np.NaN,80,np.NaN,90])
print(series_6)

0     NaN
1    70.0
2     NaN
3    80.0
4     NaN
5    90.0
dtype: float64


In [ ]:
result={'Name':['Abdul Rehman','Abdullah','Nasir','Ali','Ameen'],
        'Roll No':[1010,1020,1030,1040,1050],
         'Math':[84,88,92,76,62],
         'Chemistry':[79,70,67,69,56],
        'Physics':[89,76,72,71,66],
         'English':[69,71,65,62,59]}

df=pd.DataFrame(result)
df

Name  Roll No  Math  Chemistry  Physics  English
0  Abdul Rehman     1010    84         79       89       69
1      Abdullah     1020    88         70       76       71
2         Nasir     1030    92         67       72       65
3           Ali     1040    76         69       71       62
4         Ameen     1050    62         56       66       59

In [ ]:
df.loc[23]

Name  Roll No  Math  Chemistry  Physics  English
2  Nasir     1030    92         67       72       65
3    Ali     1040    76         69       71       62

In [ ]:
df.loc[2]

Name         Nasir
Roll No       1030
Math            92
Chemistry       67
Physics         72
English         65
Name: 2, dtype: object

In [ ]:
df.iloc[2]

Name         Nasir
Roll No       1030
Math            92
Chemistry       67
Physics         72
English         65
Name: 2, dtype: object

In [ ]:
df.loc[2:4]

Name  Roll No  Math  Chemistry  Physics  English
2  Nasir     1030    92         67       72       65
3    Ali     1040    76         69       71       62
4  Ameen     1050    62         56       66       59

In [ ]:
df.iloc[2:4]

Name  Roll No  Math  Chemistry  Physics  English
2  Nasir     1030    92         67       72       65
3    Ali     1040    76         69       71       62

In [ ]:
df.loc[[2,4,1],["Math"]]

Math
2    92
4    62
1    88

In [ ]:
df.iloc[[2,4,1],[2]]

Math
2    92
4    62
1    88

In [ ]:
df.iloc[1:4,1:4]

Roll No  Math  Chemistry
1     1020    88         70
2     1030    92         67
3     1040    76         69

In [ ]:
df["Math"]>=80

0     True
1     True
2     True
3    False
4    False
Name: Math, dtype: bool

In [ ]:
df[df["Math"]>=80]

Name  Roll No  Math  Chemistry  Physics  English
0  Abdul Rehman     1010    84         79       89       69
1      Abdullah     1020    88         70       76       71
2         Nasir     1030    92         67       72       65

In [ ]:
df[df["Math"]>=80][["Name","Roll No"]]

Name  Roll No
0  Abdul Rehman     1010
1      Abdullah     1020
2         Nasir     1030

In [ ]:
df.drop(2)

Name  Roll No  Math  Chemistry  Physics  English
0  Abdul Rehman     1010    84         79       89       69
1      Abdullah     1020    88         70       76       71
3           Ali     1040    76         69       71       62
4         Ameen     1050    62         56       66       59

In [ ]:
df= np.arange(16).reshape(4,4)
index=["Karachi","Lahore","Islamabad","Queta"]
colom=["one","two","three","four"]

print(df)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
